#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/christophe/Programs/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/christophe/Programs/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/christophe/Documents/Models/BBP Extracted/L23_SBC_dNAC222_5/x86_64/.libs/libnrnmech.so" "$@"
