#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/stefano/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/stefano/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/stefano/GIT_UANeurons/UANeurons/Code/Neuron/Model Runner/x86_64/.libs/libnrnmech.so" "$@"
